//HintName: GlobalEvents.g.cs
// <auto-generated/>
#nullable enable
public partial class GlobalEvents : global::Natrix.Core.Components.BaseEmits
{
    public global::System.Action<int>? OnNotify { get; init; } = null;

    public partial void Notify(int code)
    {
        if (Disabled) return;
        OnNotify?.Invoke(code);
    }
}
