//HintName: GeneratedEventsAttribute.g.cs
// <auto-generated/>
#nullable enable

namespace Natrix.Core.Components;

[System.AttributeUsage(System.AttributeTargets.Class)]
public sealed class GeneratedEventsAttribute : System.Attribute { }