<Project>
    <PropertyGroup>
        <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishRelease>true</PublishRelease>
        <IsAotCompatible>true</IsAotCompatible>

        <WarningsNotAsErrors>CS8620;CS8625;IL3000</WarningsNotAsErrors>

        <NatrixApiVersion Condition="'$(NatrixApiVersion)' == ''">0.1.0</NatrixApiVersion>
        <NatrixCoreVersion Condition="'$(NatrixCoreVersion)' == ''">0.1.0</NatrixCoreVersion>
        <NatrixTailwindVersion Condition="'$(NatrixTailwindVersion)' == ''">0.1.0</NatrixTailwindVersion>
        <NatrixTemplatesVersion Condition="'$(NatrixTemplatesVersion)' == ''">0.2.0</NatrixTemplatesVersion>

        <!-- By default, don't create NuGet packages for projects -->
        <IsPackable>false</IsPackable>
    </PropertyGroup>
</Project>
 