<Project>
    <PropertyGroup>
        <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
        <LangVersion>14.0</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsAotCompatible>true</IsAotCompatible>

        <NatrixApiVersion Condition="'$(NatrixApiVersion)' == ''">0.2.0</NatrixApiVersion>
        <NatrixCoreVersion Condition="'$(NatrixCoreVersion)' == ''">0.3.0</NatrixCoreVersion>
        <NatrixTailwindVersion Condition="'$(NatrixTailwindVersion)' == ''">0.3.0</NatrixTailwindVersion>
        <NatrixTemplatesVersion Condition="'$(NatrixTemplatesVersion)' == ''">0.10.0</NatrixTemplatesVersion>

        <!-- By default, don't create NuGet packages for projects -->
        <IsPackable>false</IsPackable>
    </PropertyGroup>
</Project>
 