using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Natrix.TailwindCss.Generators;

/// <summary>Names for the pipeline steps the incrementality tests assert on.</summary>
internal static class TrackingNames
{
    public const string Candidates = nameof(Candidates);
    public const string Stylesheets = nameof(Stylesheets);
    public const string Methods = nameof(Methods);
}

[Generator]
public class TailwindCssGenerator : IIncrementalGenerator
{
    private const string AttributeName = "Natrix.TailwindCss.GeneratedTailwindCssAttribute";

    private static readonly DiagnosticDescriptor CompilationFailed = new(
        id: "TWCSS001",
        title: "Tailwind CSS compilation failed",
        messageFormat: "Tailwind CSS compilation failed: {0}",
        category: "TailwindCss",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor StylesheetNotFound = new(
        id: "TWCSS002",
        title: "Tailwind CSS entry stylesheet not found",
        messageFormat: "The entry stylesheet '{0}' was not found. The path is relative to this source file, and "
            + "stylesheets are the ones the project lists as AdditionalFiles; add "
            + "<AdditionalFiles Include=\"Styles\\**\\*.css\" /> or an item for this file.",
        category: "TailwindCss",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor EngineUnavailable = new(
        id: "TWCSS003",
        title: "Tailwind CSS engine unavailable",
        messageFormat: "The Tailwind CSS engine could not be initialized for '{0}': {1}",
        category: "TailwindCss",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor SourceDirectiveIgnored = new(
        id: "TWCSS004",
        title: "@source directive is ignored",
        messageFormat: "'@source' is ignored: Natrix collects candidates from the string literals in the "
            + "compilation, not from files on disk",
        category: "TailwindCss",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor InvalidMethodSignature = new(
        id: "TWCSS005",
        title: "Invalid [GeneratedTailwindCss] method",
        messageFormat: "'{0}' must be a partial method that returns string and takes no parameters",
        category: "TailwindCss",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("GeneratedTailwindCssAttribute.g.cs", SourceText.From("""
                // <auto-generated/>
                #nullable enable

                namespace Natrix.TailwindCss;

                /// <summary>
                /// Generates the body of a partial method, returning the Tailwind CSS
                /// compiled from an entry stylesheet.
                /// </summary>
                [System.AttributeUsage(System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
                public sealed class GeneratedTailwindCssAttribute : System.Attribute
                {
                    /// <param name="stylesheetPath">
                    /// Path to the entry stylesheet, relative to the source file this
                    /// attribute is written in, for example "Styles/app.css".
                    /// </param>
                    public GeneratedTailwindCssAttribute(string stylesheetPath)
                        => StylesheetPath = stylesheetPath;

                    /// <summary>Path to the entry stylesheet, relative to the declaring source file.</summary>
                    public string StylesheetPath { get; }
                }
                """, Encoding.UTF8)));

        // Tailwind generates a utility only when something references it, so the
        // candidate set is every whitespace-separated word in every string
        // literal. Sorted and deduplicated so that reordering source, or adding a
        // literal that repeats an existing class, does not invalidate the cache.
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is LiteralExpressionSyntax literal
                    && literal.IsKind(SyntaxKind.StringLiteralExpression),
                transform: static (ctx, _) => ((LiteralExpressionSyntax)ctx.Node).Token.ValueText)
            .Collect()
            .Select(static (literals, _) => new EquatableArray<string>(literals
                .SelectMany(static literal => literal.Split(
                    new[] { ' ', '\t', '\n', '\r' }, StringSplitOptions.RemoveEmptyEntries))
                .Distinct(StringComparer.Ordinal)
                .OrderBy(static candidate => candidate, StringComparer.Ordinal)
                .ToImmutableArray()))
            .WithTrackingName(TrackingNames.Candidates);

        var engineDir = context.AnalyzerConfigOptionsProvider
            .Select(static (provider, _) =>
            {
                provider.GlobalOptions.TryGetValue("build_property.NatrixTailwindEngineDir", out var dir);
                return dir ?? "";
            });

        // Every .css file the project exposes as an AdditionalFile. Reading them
        // through this provider is what makes Roslyn re-run the generator when
        // one of them changes.
        //
        // Combining with AnalyzerConfigOptionsProvider is what gives access to
        // per-file metadata. That provider has no value equality, so this step
        // re-runs on every compilation — but Select projects to an equatable
        // Stylesheet, so downstream steps still compare by value and the
        // expensive compile stays cached.
        var stylesheets = context.AdditionalTextsProvider
            .Where(static text => text.Path.EndsWith(".css", StringComparison.OrdinalIgnoreCase))
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Select(static (pair, ct) =>
            {
                var (text, configOptions) = pair;

                configOptions.GetOptions(text)
                    .TryGetValue("build_metadata.AdditionalFiles.TailwindModule", out var module);

                return new Stylesheet(
                    StylesheetResolver.Normalize(text.Path),
                    text.GetText(ct)?.ToString() ?? "",
                    module);
            })
            .Collect()
            // AdditionalFiles order follows MSBuild evaluation, so sort to keep
            // the pipeline value stable.
            .Select(static (all, _) => new EquatableArray<Stylesheet>(all
                .OrderBy(static sheet => sheet.Path, StringComparer.Ordinal)
                .ToImmutableArray()))
            .WithTrackingName(TrackingNames.Stylesheets);

        var methods = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeName,
                predicate: static (node, _) => node is MethodDeclarationSyntax,
                transform: static (ctx, ct) => GetMethodInfo(ctx, ct))
            .Where(static info => info is not null)
            .WithTrackingName(TrackingNames.Methods);

        context.RegisterSourceOutput(
            methods.Combine(stylesheets).Combine(candidates).Combine(engineDir),
            static (spc, source) => Execute(
                spc,
                source.Left.Left.Left!,
                source.Left.Left.Right,
                source.Left.Right,
                source.Right));
    }

    /// <summary>
    /// A source location reduced to value-equatable parts.
    /// </summary>
    /// <remarks>
    /// Holding a <see cref="Location"/> in a pipeline model would keep its
    /// <see cref="SyntaxTree"/> alive and make the model compare unequal on every
    /// edit, defeating caching.
    /// </remarks>
    private readonly record struct LocationInfo(string FilePath, TextSpan Span, LinePositionSpan LineSpan)
    {
        public static LocationInfo? From(SyntaxNode? node) =>
            node is null ? null : new LocationInfo(
                node.SyntaxTree.FilePath,
                node.Span,
                node.SyntaxTree.GetLineSpan(node.Span).Span);

        public Location ToLocation() => Location.Create(FilePath, Span, LineSpan);
    }

    private sealed record MethodInfo(
        string MethodName,
        string ContainingNamespace,
        string ContainingTypeName,
        string TypeKeyword,
        string Accessibility,
        bool IsStatic,
        string StylesheetPath,
        string SourceDirectory,
        bool HasValidSignature,
        LocationInfo? Location);

    private static MethodInfo? GetMethodInfo(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not IMethodSymbol method)
            return null;

        var attribute = ctx.Attributes.FirstOrDefault();
        if (attribute is null || attribute.ConstructorArguments.Length < 1)
            return null;

        var containingType = method.ContainingType;

        return new MethodInfo(
            MethodName: method.Name,
            ContainingNamespace: containingType.ContainingNamespace.IsGlobalNamespace
                ? ""
                : containingType.ContainingNamespace.ToDisplayString(),
            ContainingTypeName: containingType.Name,
            TypeKeyword: containingType.IsRecord
                ? containingType.IsValueType ? "record struct" : "record"
                : containingType.IsValueType ? "struct" : "class",
            Accessibility: method.DeclaredAccessibility switch
            {
                Accessibility.Public => "public",
                Accessibility.Internal => "internal",
                Accessibility.Private => "private",
                Accessibility.Protected => "protected",
                Accessibility.ProtectedOrInternal => "protected internal",
                Accessibility.ProtectedAndInternal => "private protected",
                _ => "public",
            },
            IsStatic: method.IsStatic,
            StylesheetPath: attribute.ConstructorArguments[0].Value as string ?? "",
            // The entry stylesheet is named relative to the file the attribute is
            // written in, so that is what it has to be resolved against.
            SourceDirectory: StylesheetResolver.DirectoryOf(
                StylesheetResolver.Normalize(ctx.TargetNode.SyntaxTree.FilePath)),
            HasValidSignature: method.IsPartialDefinition
                && method.Parameters.Length == 0
                && method.ReturnType.SpecialType == SpecialType.System_String,
            Location: LocationInfo.From(attribute.ApplicationSyntaxReference?.GetSyntax(ct)));
    }

    private static void Execute(
        SourceProductionContext spc,
        MethodInfo info,
        EquatableArray<Stylesheet> stylesheets,
        EquatableArray<string> candidates,
        string engineDir)
    {
        var location = info.Location?.ToLocation() ?? Location.None;

        if (!info.HasValidSignature)
        {
            spc.ReportDiagnostic(Diagnostic.Create(
                InvalidMethodSignature, location, $"{info.ContainingTypeName}.{info.MethodName}"));
            return;
        }

        var resolver = new StylesheetResolver(stylesheets);
        var entryPath = StylesheetResolver.Resolve(info.SourceDirectory, info.StylesheetPath);

        if (!resolver.TryGet(entryPath, out var entryCss))
        {
            spc.ReportDiagnostic(Diagnostic.Create(StylesheetNotFound, location, info.StylesheetPath));
            return;
        }

        // The base for the entry stylesheet is its own directory, exactly as it is
        // for every file the resolver hands back afterwards. From here on the
        // resolver only ever sees the base Tailwind passes it.
        var result = TailwindCompiler.Compile(
            ResolveEngineDir(engineDir),
            entryCss,
            StylesheetResolver.DirectoryOf(entryPath),
            candidates.AsImmutableArray(),
            resolver.Load);

        switch (result.Status)
        {
            case CompileStatus.EngineError:
                spc.ReportDiagnostic(Diagnostic.Create(
                    EngineUnavailable, location, SafeRuntimeIdentifier(), result.Payload));
                return;

            case CompileStatus.StylesheetError:
                spc.ReportDiagnostic(Diagnostic.Create(CompilationFailed, location, FirstLine(result.Payload)));
                return;
        }

        // Warn once per compiled stylesheet set, not once per occurrence.
        if (UsesSourceDirective(entryCss) || resolver.Served.Any(UsesSourceDirective))
            spc.ReportDiagnostic(Diagnostic.Create(SourceDirectiveIgnored, location));

        spc.AddSource(HintName(info), SourceText.From(Render(info, result.Payload), Encoding.UTF8));
    }

    private static string Render(MethodInfo info, string css)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        if (info.ContainingNamespace.Length > 0)
        {
            builder.AppendLine($"namespace {info.ContainingNamespace};");
            builder.AppendLine();
        }

        builder.AppendLine($"partial {info.TypeKeyword} {info.ContainingTypeName}");
        builder.AppendLine("{");
        builder.AppendLine(
            $"    {info.Accessibility} {(info.IsStatic ? "static " : "")}partial string {info.MethodName}() =>");
        builder.Append(RawStringLiteral(css));
        builder.AppendLine(";");
        builder.AppendLine("}");

        return builder.ToString();
    }

    /// <summary>
    /// Wraps CSS in a raw string literal wide enough to contain it.
    /// </summary>
    /// <remarks>
    /// A fixed <c>"""</c> fence breaks on CSS that itself contains three or more
    /// consecutive quotes, which is reachable through <c>content:</c> values. The
    /// fence has to be at least one quote longer than the longest run in the
    /// content, and both delimiters sit at column zero so no indentation is
    /// stripped from the CSS.
    /// </remarks>
    internal static string RawStringLiteral(string content)
    {
        // Line endings are normalized so the generated file, and the snapshots
        // taken of it, are identical on Windows and Unix.
        var body = content.Replace("\r\n", "\n").Replace('\r', '\n');

        var longestRun = 0;
        var run = 0;
        foreach (var c in body)
        {
            if (c == '"')
            {
                run++;
                if (run > longestRun)
                    longestRun = run;
            }
            else
            {
                run = 0;
            }
        }

        var fence = new string('"', Math.Max(3, longestRun + 1));

        // The closing delimiter must start its own line.
        if (body.Length == 0 || body[body.Length - 1] != '\n')
            body += "\n";

        return fence + "\n" + body + fence;
    }

    /// <summary>
    /// Falls back to a directory next to this assembly when MSBuild did not
    /// supply one, which is how the generator's own tests find the payload.
    /// </summary>
    private static string ResolveEngineDir(string engineDir)
    {
        if (engineDir.Length > 0)
            return engineDir;

#pragma warning disable IL3000 // Analyzers always run from a real file on disk.
        var assemblyDir = Path.GetDirectoryName(typeof(TailwindCssGenerator).Assembly.Location);
#pragma warning restore IL3000

        return assemblyDir is null ? "" : Path.Combine(assemblyDir, "tailwind");
    }

    private static string SafeRuntimeIdentifier()
    {
        try
        {
            return TailwindCompiler.GetRuntimeIdentifier();
        }
        catch (PlatformNotSupportedException)
        {
            return "unsupported platform";
        }
    }

    private static bool UsesSourceDirective(string css) => css
        .Split('\n')
        .Any(static line => line.TrimStart().StartsWith("@source", StringComparison.Ordinal));

    private static string FirstLine(string message)
    {
        var index = message.IndexOf('\n');
        return (index < 0 ? message : message.Substring(0, index)).TrimEnd('\r');
    }

    private static string HintName(MethodInfo info) => info.ContainingNamespace.Length == 0
        ? $"{info.ContainingTypeName}.{info.MethodName}.g.cs"
        : $"{info.ContainingNamespace}.{info.ContainingTypeName}.{info.MethodName}.g.cs";
}
