// In the browser this is an ordinary test application. On the host (dotnet test, IDE
// test explorers) the same assembly launches headless Chromium and runs itself there.
// SelfRegisteredExtensions is generated by Microsoft.Testing.Platform from the test
// framework packages this project references.
return await Natrix.Browser.TestHost.BrowserTestHost.RunAsync(args, SelfRegisteredExtensions.AddSelfRegisteredExtensions);
