using Natrix.Core.Components;
using Natrix.Dom.Components;
using Natrix.Signals;

namespace Natrix.Dom.TestCases;

/// <summary>
/// Every DOM component rendered without props: its tag, and its children unless it is a void element.
/// </summary>
public static class ElementCases
{
    public static IEnumerable<DomCase> All() =>
    [
        Case("DomText", () => Text("x"), "x"),
        Case("DomComment", () => new DomComment { Data = new Signal<string>("x") }, "<!--x-->"),

        Case("A", () => new A { Children = [Text("x")] }, "<a>x</a>"),
        Case("Abbr", () => new Abbr { Children = [Text("x")] }, "<abbr>x</abbr>"),
        Case("Address", () => new Address { Children = [Text("x")] }, "<address>x</address>"),
        Case("Area", () => new Area(), "<area>"),
        Case("Article", () => new Article { Children = [Text("x")] }, "<article>x</article>"),
        Case("Aside", () => new Aside { Children = [Text("x")] }, "<aside>x</aside>"),
        Case("Audio", () => new Audio { Children = [Text("x")] }, "<audio>x</audio>"),
        Case("B", () => new B { Children = [Text("x")] }, "<b>x</b>"),
        Case("Base", () => new Base(), "<base>"),
        Case("Bdi", () => new Bdi { Children = [Text("x")] }, "<bdi>x</bdi>"),
        Case("Bdo", () => new Bdo { Children = [Text("x")] }, "<bdo>x</bdo>"),
        Case("Blockquote", () => new Blockquote { Children = [Text("x")] }, "<blockquote>x</blockquote>"),
        Case("Body", () => new Body { Children = [Text("x")] }, "<body>x</body>"),
        Case("Br", () => new Br(), "<br>"),
        Case("Button", () => new Button { Children = [Text("x")] }, "<button>x</button>"),
        Case("Canvas", () => new Canvas { Children = [Text("x")] }, "<canvas>x</canvas>"),
        Case("Caption", () => new Caption { Children = [Text("x")] }, "<caption>x</caption>"),
        Case("Cite", () => new Cite { Children = [Text("x")] }, "<cite>x</cite>"),
        Case("Code", () => new Code { Children = [Text("x")] }, "<code>x</code>"),
        Case("Col", () => new Col(), "<col>"),
        Case("Colgroup", () => new Colgroup { Children = [Text("x")] }, "<colgroup>x</colgroup>"),
        Case("Data", () => new Data { Children = [Text("x")] }, "<data>x</data>"),
        Case("DataList", () => new DataList { Children = [Text("x")] }, "<datalist>x</datalist>"),
        Case("Dd", () => new Dd { Children = [Text("x")] }, "<dd>x</dd>"),
        Case("Del", () => new Del { Children = [Text("x")] }, "<del>x</del>"),
        Case("Details", () => new Details { Children = [Text("x")] }, "<details>x</details>"),
        Case("Dfn", () => new Dfn { Children = [Text("x")] }, "<dfn>x</dfn>"),
        Case("Dialog", () => new Dialog { Children = [Text("x")] }, "<dialog>x</dialog>"),
        Case("Div", () => new Div { Children = [Text("x")] }, "<div>x</div>"),
        Case("Dl", () => new Dl { Children = [Text("x")] }, "<dl>x</dl>"),
        Case("Dt", () => new Dt { Children = [Text("x")] }, "<dt>x</dt>"),
        Case("Em", () => new Em { Children = [Text("x")] }, "<em>x</em>"),
        Case("Embed", () => new Embed(), "<embed>"),
        Case("FieldSet", () => new FieldSet { Children = [Text("x")] }, "<fieldset>x</fieldset>"),
        Case("FigCaption", () => new FigCaption { Children = [Text("x")] }, "<figcaption>x</figcaption>"),
        Case("Figure", () => new Figure { Children = [Text("x")] }, "<figure>x</figure>"),
        Case("Footer", () => new Footer { Children = [Text("x")] }, "<footer>x</footer>"),
        Case("Form", () => new Form { Children = [Text("x")] }, "<form>x</form>"),
        Case("H1", () => new H1 { Children = [Text("x")] }, "<h1>x</h1>"),
        Case("H2", () => new H2 { Children = [Text("x")] }, "<h2>x</h2>"),
        Case("H3", () => new H3 { Children = [Text("x")] }, "<h3>x</h3>"),
        Case("H4", () => new H4 { Children = [Text("x")] }, "<h4>x</h4>"),
        Case("H5", () => new H5 { Children = [Text("x")] }, "<h5>x</h5>"),
        Case("H6", () => new H6 { Children = [Text("x")] }, "<h6>x</h6>"),
        Case("Head", () => new Head { Children = [Text("x")] }, "<head>x</head>"),
        Case("Header", () => new Header { Children = [Text("x")] }, "<header>x</header>"),
        Case("Hgroup", () => new Hgroup { Children = [Text("x")] }, "<hgroup>x</hgroup>"),
        Case("Hr", () => new Hr(), "<hr>"),
        Case("Html", () => new Html { Children = [Text("x")] }, "<html>x</html>"),
        Case("I", () => new I { Children = [Text("x")] }, "<i>x</i>"),
        Case("IFrame", () => new IFrame { Children = [Text("x")] }, "<iframe>x</iframe>"),
        Case("Img", () => new Img(), "<img>"),
        Case("Input", () => new Input(), "<input>"),
        Case("Ins", () => new Ins { Children = [Text("x")] }, "<ins>x</ins>"),
        Case("Kbd", () => new Kbd { Children = [Text("x")] }, "<kbd>x</kbd>"),
        Case("Label", () => new Label { Children = [Text("x")] }, "<label>x</label>"),
        Case("Legend", () => new Legend { Children = [Text("x")] }, "<legend>x</legend>"),
        Case("Li", () => new Li { Children = [Text("x")] }, "<li>x</li>"),
        Case("Link", () => new Link(), "<link>"),
        Case("Main", () => new Main { Children = [Text("x")] }, "<main>x</main>"),
        Case("Map", () => new Map { Children = [Text("x")] }, "<map>x</map>"),
        Case("Mark", () => new Mark { Children = [Text("x")] }, "<mark>x</mark>"),
        Case("Menu", () => new Menu { Children = [Text("x")] }, "<menu>x</menu>"),
        Case("Meta", () => new Meta(), "<meta>"),
        Case("Meter", () => new Meter { Children = [Text("x")] }, "<meter>x</meter>"),
        Case("Nav", () => new Nav { Children = [Text("x")] }, "<nav>x</nav>"),
        Case("Noscript", () => new Noscript { Children = [Text("x")] }, "<noscript>x</noscript>"),
        Case("Object", () => new Components.Object { Children = [Text("x")] }, "<object>x</object>"),
        Case("Ol", () => new Ol { Children = [Text("x")] }, "<ol>x</ol>"),
        Case("OptGroup", () => new OptGroup { Children = [Text("x")] }, "<optgroup>x</optgroup>"),
        Case("Option", () => new Option { Children = [Text("x")] }, "<option>x</option>"),
        Case("Output", () => new Output { Children = [Text("x")] }, "<output>x</output>"),
        Case("P", () => new P { Children = [Text("x")] }, "<p>x</p>"),
        Case("Picture", () => new Picture { Children = [Text("x")] }, "<picture>x</picture>"),
        Case("Pre", () => new Pre { Children = [Text("x")] }, "<pre>x</pre>"),
        Case("Progress", () => new Progress { Children = [Text("x")] }, "<progress>x</progress>"),
        Case("Q", () => new Q { Children = [Text("x")] }, "<q>x</q>"),
        Case("Rp", () => new Rp { Children = [Text("x")] }, "<rp>x</rp>"),
        Case("Rt", () => new Rt { Children = [Text("x")] }, "<rt>x</rt>"),
        Case("Ruby", () => new Ruby { Children = [Text("x")] }, "<ruby>x</ruby>"),
        Case("S", () => new S { Children = [Text("x")] }, "<s>x</s>"),
        Case("Samp", () => new Samp { Children = [Text("x")] }, "<samp>x</samp>"),
        Case("Script", () => new Script { Children = [Text("x")] }, "<script>x</script>"),
        Case("Search", () => new Search { Children = [Text("x")] }, "<search>x</search>"),
        Case("Section", () => new Section { Children = [Text("x")] }, "<section>x</section>"),
        Case("Select", () => new Select { Children = [Text("x")] }, "<select>x</select>"),
        Case("Slot", () => new Slot { Children = [Text("x")] }, "<slot>x</slot>"),
        Case("Small", () => new Small { Children = [Text("x")] }, "<small>x</small>"),
        Case("Source", () => new Source(), "<source>"),
        Case("Span", () => new Span { Children = [Text("x")] }, "<span>x</span>"),
        Case("Strong", () => new Strong { Children = [Text("x")] }, "<strong>x</strong>"),
        Case("Style", () => new Style { Children = [Text("x")] }, "<style>x</style>"),
        Case("Sub", () => new Sub { Children = [Text("x")] }, "<sub>x</sub>"),
        Case("Summary", () => new Summary { Children = [Text("x")] }, "<summary>x</summary>"),
        Case("Sup", () => new Sup { Children = [Text("x")] }, "<sup>x</sup>"),
        Case("Table", () => new Table { Children = [Text("x")] }, "<table>x</table>"),
        Case("Tbody", () => new Tbody { Children = [Text("x")] }, "<tbody>x</tbody>"),
        Case("Td", () => new Td { Children = [Text("x")] }, "<td>x</td>"),
        Case("Template", () => new Template { Children = [Text("x")] }, "<template>x</template>"),
        Case("TextArea", () => new TextArea { Children = [Text("x")] }, "<textarea>x</textarea>"),
        Case("Tfoot", () => new Tfoot { Children = [Text("x")] }, "<tfoot>x</tfoot>"),
        Case("Th", () => new Th { Children = [Text("x")] }, "<th>x</th>"),
        Case("Thead", () => new Thead { Children = [Text("x")] }, "<thead>x</thead>"),
        Case("Time", () => new Time { Children = [Text("x")] }, "<time>x</time>"),
        Case("Title", () => new Title { Children = [Text("x")] }, "<title>x</title>"),
        Case("Tr", () => new Tr { Children = [Text("x")] }, "<tr>x</tr>"),
        Case("Track", () => new Track(), "<track>"),
        Case("U", () => new U { Children = [Text("x")] }, "<u>x</u>"),
        Case("Ul", () => new Ul { Children = [Text("x")] }, "<ul>x</ul>"),
        Case("Var", () => new Var { Children = [Text("x")] }, "<var>x</var>"),
        Case("Video", () => new Video { Children = [Text("x")] }, "<video>x</video>"),
        Case("Wbr", () => new Wbr(), "<wbr>"),
    ];

    private static DomText Text(string text) => new() { Text = new Signal<string>(text) };

    private static DomCase Case(string name, Func<IComponent> create, string html) => new(name, create, html);
}
