using Natrix.Dom.Components;
using Natrix.Signals;

namespace Natrix.Dom.TestCases;

/// <summary>
/// Every prop of <see cref="GlobalElementComponentProps{TElement}"/> and
/// <see cref="GlobalHtmlComponentProps{TElement}"/>. Every component inherits them through the same
/// descriptors, so they are checked once, on <see cref="Div"/>.
/// </summary>
public static class GlobalPropCases
{
    public static IEnumerable<DomCase> All() =>
    [
        Case("Role", new DivProps { Role = S<string?>("switch") }, """<div role="switch"></div>"""),
        Case("Role.Null", new DivProps { Role = S<string?>(null) }, """<div></div>"""),
        Case("AriaActiveDescendant", new DivProps { AriaActiveDescendant = S<string?>("opt-1") }, """<div aria-activedescendant="opt-1"></div>"""),
        Case("AriaAtomic", new DivProps { AriaAtomic = S(true) }, """<div aria-atomic="true"></div>"""),
        Case("AriaAtomic.False", new DivProps { AriaAtomic = S(false) }, """<div aria-atomic="false"></div>"""),
        Case("AriaAutoComplete", new DivProps { AriaAutoComplete = S<string?>("list") }, """<div aria-autocomplete="list"></div>"""),
        Case("AriaBrailleLabel", new DivProps { AriaBrailleLabel = S<string?>("btn") }, """<div aria-braillelabel="btn"></div>"""),
        Case("AriaBrailleRoleDescription", new DivProps { AriaBrailleRoleDescription = S<string?>("sw") }, """<div aria-brailleroledescription="sw"></div>"""),
        Case("AriaBusy", new DivProps { AriaBusy = S(true) }, """<div aria-busy="true"></div>"""),
        Case("AriaBusy.False", new DivProps { AriaBusy = S(false) }, """<div aria-busy="false"></div>"""),
        Case("AriaChecked", new DivProps { AriaChecked = S<string?>("mixed") }, """<div aria-checked="mixed"></div>"""),
        Case("AriaColCount", new DivProps { AriaColCount = S(2) }, """<div aria-colcount="2"></div>"""),
        Case("AriaColIndex", new DivProps { AriaColIndex = S(2) }, """<div aria-colindex="2"></div>"""),
        Case("AriaColIndexText", new DivProps { AriaColIndexText = S<string?>("B") }, """<div aria-colindextext="B"></div>"""),
        Case("AriaColSpan", new DivProps { AriaColSpan = S(2) }, """<div aria-colspan="2"></div>"""),
        Case("AriaControls", new DivProps { AriaControls = S<string?>("panel") }, """<div aria-controls="panel"></div>"""),
        Case("AriaCurrent", new DivProps { AriaCurrent = S<string?>("page") }, """<div aria-current="page"></div>"""),
        Case("AriaDescribedBy", new DivProps { AriaDescribedBy = S<string?>("hint") }, """<div aria-describedby="hint"></div>"""),
        Case("AriaDescription", new DivProps { AriaDescription = S<string?>("More") }, """<div aria-description="More"></div>"""),
        Case("AriaDetails", new DivProps { AriaDetails = S<string?>("details") }, """<div aria-details="details"></div>"""),
        Case("AriaDisabled", new DivProps { AriaDisabled = S(true) }, """<div aria-disabled="true"></div>"""),
        Case("AriaDisabled.False", new DivProps { AriaDisabled = S(false) }, """<div aria-disabled="false"></div>"""),
        Case("AriaErrorMessage", new DivProps { AriaErrorMessage = S<string?>("error") }, """<div aria-errormessage="error"></div>"""),
        Case("AriaExpanded", new DivProps { AriaExpanded = S<string?>("true") }, """<div aria-expanded="true"></div>"""),
        Case("AriaFlowTo", new DivProps { AriaFlowTo = S<string?>("next") }, """<div aria-flowto="next"></div>"""),
        Case("AriaHasPopup", new DivProps { AriaHasPopup = S<string?>("menu") }, """<div aria-haspopup="menu"></div>"""),
        Case("AriaHidden", new DivProps { AriaHidden = S(true) }, """<div aria-hidden="true"></div>"""),
        Case("AriaHidden.False", new DivProps { AriaHidden = S(false) }, """<div aria-hidden="false"></div>"""),
        Case("AriaInvalid", new DivProps { AriaInvalid = S<string?>("grammar") }, """<div aria-invalid="grammar"></div>"""),
        Case("AriaKeyShortcuts", new DivProps { AriaKeyShortcuts = S<string?>("Alt+K") }, """<div aria-keyshortcuts="Alt+K"></div>"""),
        Case("AriaLabel", new DivProps { AriaLabel = S<string?>("Close") }, """<div aria-label="Close"></div>"""),
        Case("AriaLabelledBy", new DivProps { AriaLabelledBy = S<string?>("heading") }, """<div aria-labelledby="heading"></div>"""),
        Case("AriaLevel", new DivProps { AriaLevel = S(2) }, """<div aria-level="2"></div>"""),
        Case("AriaLive", new DivProps { AriaLive = S<string?>("polite") }, """<div aria-live="polite"></div>"""),
        Case("AriaModal", new DivProps { AriaModal = S(true) }, """<div aria-modal="true"></div>"""),
        Case("AriaModal.False", new DivProps { AriaModal = S(false) }, """<div aria-modal="false"></div>"""),
        Case("AriaMultiLine", new DivProps { AriaMultiLine = S(true) }, """<div aria-multiline="true"></div>"""),
        Case("AriaMultiLine.False", new DivProps { AriaMultiLine = S(false) }, """<div aria-multiline="false"></div>"""),
        Case("AriaMultiSelectable", new DivProps { AriaMultiSelectable = S(true) }, """<div aria-multiselectable="true"></div>"""),
        Case("AriaMultiSelectable.False", new DivProps { AriaMultiSelectable = S(false) }, """<div aria-multiselectable="false"></div>"""),
        Case("AriaOrientation", new DivProps { AriaOrientation = S<string?>("vertical") }, """<div aria-orientation="vertical"></div>"""),
        Case("AriaOwns", new DivProps { AriaOwns = S<string?>("popup") }, """<div aria-owns="popup"></div>"""),
        Case("AriaPlaceholder", new DivProps { AriaPlaceholder = S<string?>("Search") }, """<div aria-placeholder="Search"></div>"""),
        Case("AriaPosInSet", new DivProps { AriaPosInSet = S(2) }, """<div aria-posinset="2"></div>"""),
        Case("AriaPressed", new DivProps { AriaPressed = S<string?>("true") }, """<div aria-pressed="true"></div>"""),
        Case("AriaReadOnly", new DivProps { AriaReadOnly = S(true) }, """<div aria-readonly="true"></div>"""),
        Case("AriaReadOnly.False", new DivProps { AriaReadOnly = S(false) }, """<div aria-readonly="false"></div>"""),
        Case("AriaRelevant", new DivProps { AriaRelevant = S<string?>("additions") }, """<div aria-relevant="additions"></div>"""),
        Case("AriaRequired", new DivProps { AriaRequired = S(true) }, """<div aria-required="true"></div>"""),
        Case("AriaRequired.False", new DivProps { AriaRequired = S(false) }, """<div aria-required="false"></div>"""),
        Case("AriaRoleDescription", new DivProps { AriaRoleDescription = S<string?>("slide") }, """<div aria-roledescription="slide"></div>"""),
        Case("AriaRowCount", new DivProps { AriaRowCount = S(2) }, """<div aria-rowcount="2"></div>"""),
        Case("AriaRowIndex", new DivProps { AriaRowIndex = S(2) }, """<div aria-rowindex="2"></div>"""),
        Case("AriaRowIndexText", new DivProps { AriaRowIndexText = S<string?>("Row 2") }, """<div aria-rowindextext="Row 2"></div>"""),
        Case("AriaRowSpan", new DivProps { AriaRowSpan = S(2) }, """<div aria-rowspan="2"></div>"""),
        Case("AriaSelected", new DivProps { AriaSelected = S(true) }, """<div aria-selected="true"></div>"""),
        Case("AriaSelected.False", new DivProps { AriaSelected = S(false) }, """<div aria-selected="false"></div>"""),
        Case("AriaSetSize", new DivProps { AriaSetSize = S(2) }, """<div aria-setsize="2"></div>"""),
        Case("AriaSort", new DivProps { AriaSort = S<string?>("ascending") }, """<div aria-sort="ascending"></div>"""),
        Case("AriaValueMax", new DivProps { AriaValueMax = S(0.5) }, """<div aria-valuemax="0.5"></div>"""),
        Case("AriaValueMin", new DivProps { AriaValueMin = S(0.5) }, """<div aria-valuemin="0.5"></div>"""),
        Case("AriaValueNow", new DivProps { AriaValueNow = S(0.5) }, """<div aria-valuenow="0.5"></div>"""),
        Case("AriaValueText", new DivProps { AriaValueText = S<string?>("Half") }, """<div aria-valuetext="Half"></div>"""),
        Case("AccessKey", new DivProps { AccessKey = S("k") }, """<div accesskey="k"></div>"""),
        Case("Autocapitalize", new DivProps { Autocapitalize = S("words") }, """<div autocapitalize="words"></div>"""),
        Case("Autocorrect", new DivProps { Autocorrect = S(true) }, """<div autocorrect="on"></div>"""),
        Case("Autocorrect.False", new DivProps { Autocorrect = S(false) }, """<div autocorrect="off"></div>"""),
        Case("Autofocus", new DivProps { Autofocus = S(true) }, """<div autofocus></div>"""),
        Case("Autofocus.False", new DivProps { Autofocus = S(false) }, """<div></div>"""),
        Case("Class", new DivProps { Class = S("card active") }, """<div class="card active"></div>"""),
        Case("ContentEditable", new DivProps { ContentEditable = S("true") }, """<div contenteditable="true"></div>"""),
        Case("Data", new DivProps { Data = S<IDictionary<string, string>>(new Dictionary<string, string> { ["a"] = "1", ["b"] = "2" }) }, """<div data-a="1" data-b="2"></div>"""),
        Case("Dir", new DivProps { Dir = S("rtl") }, """<div dir="rtl"></div>"""),
        Case("Draggable", new DivProps { Draggable = S(true) }, """<div draggable="true"></div>"""),
        Case("Draggable.False", new DivProps { Draggable = S(false) }, """<div draggable="false"></div>"""),
        Case("EnterKeyHint", new DivProps { EnterKeyHint = S("send") }, """<div enterkeyhint="send"></div>"""),
        Case("Hidden.True", new DivProps { Hidden = S(HiddenOption.True) }, """<div hidden></div>"""),
        Case("Hidden.False", new DivProps { Hidden = S(HiddenOption.False) }, """<div></div>"""),
        Case("Hidden.UntilFound", new DivProps { Hidden = S(HiddenOption.UntilFound) }, """<div hidden="until-found"></div>"""),
        Case("Id", new DivProps { Id = S("main") }, """<div id="main"></div>"""),
        Case("Inert", new DivProps { Inert = S(true) }, """<div inert></div>"""),
        Case("Inert.False", new DivProps { Inert = S(false) }, """<div></div>"""),
        Case("InputMode", new DivProps { InputMode = S("numeric") }, """<div inputmode="numeric"></div>"""),
        Case("Lang", new DivProps { Lang = S("en") }, """<div lang="en"></div>"""),
        Case("Nonce", new DivProps { Nonce = S("abc") }, """<div nonce="abc"></div>""", browserHtml: """<div></div>""", property: ("nonce", "abc")),
        Case("Part", new DivProps { Part = S("label") }, """<div part="label"></div>"""),
        Case("Popover", new DivProps { Popover = S<string?>("auto") }, """<div popover="auto"></div>"""),
        Case("Popover.Null", new DivProps { Popover = S<string?>(null) }, """<div></div>"""),
        Case("Slot", new DivProps { Slot = S("header") }, """<div slot="header"></div>"""),
        Case("Spellcheck", new DivProps { Spellcheck = S(true) }, """<div spellcheck="true"></div>"""),
        Case("Spellcheck.False", new DivProps { Spellcheck = S(false) }, """<div spellcheck="false"></div>"""),
        Case("Style", new DivProps { Style = S("color: red;") }, """<div style="color: red;"></div>"""),
        Case("TabIndex", new DivProps { TabIndex = S(2) }, """<div tabindex="2"></div>"""),
        Case("Title", new DivProps { Title = S("Tip") }, """<div title="Tip"></div>"""),
        Case("Translate", new DivProps { Translate = S(true) }, """<div translate="yes"></div>"""),
        Case("Translate.False", new DivProps { Translate = S(false) }, """<div translate="no"></div>"""),
        Case("VirtualKeyboardPolicy", new DivProps { VirtualKeyboardPolicy = S("manual") }, """<div virtualkeyboardpolicy="manual"></div>"""),
        Case("WritingSuggestions", new DivProps { WritingSuggestions = S("false") }, """<div writingsuggestions="false"></div>"""),
    ];

    private static Signal<T> S<T>(T value) => new(value);

    private static DomCase Case(
        string name,
        DivProps props,
        string html,
        string? browserHtml = null,
        (string, object)? property = null,
        string? browserIssue = null) =>
        new(name, () => new Div { Props = props }, html)
        {
            BrowserHtml = browserHtml,
            Property = property,
            BrowserIssue = browserIssue,
        };
}
