//HintName: GeneratedTailwindCssAttribute.g.cs
// <auto-generated/>
#nullable enable

namespace Natrix.TailwindCss;

[System.AttributeUsage(System.AttributeTargets.Method)]
public sealed class GeneratedTailwindCssAttribute : System.Attribute
{
    public GeneratedTailwindCssAttribute(string css, params string[] pairs) { }
}