//HintName: GeneratedTailwindCssAttribute.g.cs
// <auto-generated/>
#nullable enable

namespace Natrix.TailwindCss;

/// <summary>
/// Generates the body of a partial method, returning the Tailwind CSS
/// compiled from an entry stylesheet.
/// </summary>
[System.AttributeUsage(System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
public sealed class GeneratedTailwindCssAttribute : System.Attribute
{
    /// <param name="stylesheetPath">
    /// Path to the entry stylesheet, relative to the source file this
    /// attribute is written in, for example "Styles/app.css".
    /// </param>
    public GeneratedTailwindCssAttribute(string stylesheetPath)
        => StylesheetPath = stylesheetPath;

    /// <summary>Path to the entry stylesheet, relative to the declaring source file.</summary>
    public string StylesheetPath { get; }
}