<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <WarningsNotAsErrors>$(WarningsNotAsErrors);CS8620</WarningsNotAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="TUnit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Natrix.Signals\Natrix.Signals.csproj"/>
    </ItemGroup>

</Project>
