<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
    <PropertyGroup>
        <RunAOTCompilation>true</RunAOTCompilation>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Natrix.Browser\Natrix.Browser.csproj" Watch="false" />
        <ProjectReference Include="..\..\src\Natrix.Core.Generators\Natrix.Core.Generators.csproj"
            OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\..\src\Natrix.TailwindCss\Natrix.TailwindCss.csproj" />
        <ProjectReference
            Include="..\..\src\Natrix.TailwindCss.Generators\Natrix.TailwindCss.Generators.csproj"
            OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <Import Project="..\..\src\Natrix.Core\targets\Natrix.Core.StaticAssets.targets" />
    <Import
        Project="..\..\src\Natrix.TailwindCss.Generators\targets\Natrix.TailwindCss.Generators.targets" />
</Project>