//HintName: MyApp.Styles.GetCss.g.cs
// <auto-generated/>
#nullable enable

namespace MyApp;

partial class Styles
{
    public static partial string GetCss() =>
"""
/*! tailwindcss v4.3.0 | MIT License | https://tailwindcss.com */
@layer theme {
  :root, :host {
    --color-red-500: oklch(63.7% 0.237 25.331);
    --spacing: 0.25rem;
  }
}
@layer utilities {
  .bg-red-500 {
    background-color: var(--color-red-500);
  }
  .p-4 {
    padding: calc(var(--spacing) * 4);
  }
}
""";
}
